---
apiVersion: v1
kind: Service
metadata:
  name: conf-details-svc 
  namespace: ambassador
spec:
  type: ClusterIP
  selector:
    app: conf-details-svc 
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-details-svc 
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conf-details-svc 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: conf-details-svc
    spec:
      containers:
      - name: backend
        image: shahadarsh/conf-details-svc:2.0
        ports:
        - name: http
          containerPort: 8080
