apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: conf-details-svc
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: conf-details-svc
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: shahadarsh/conf-details-svc:1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080 
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
