apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conf-details-svc-02
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: conf-details-svc
        version: "02"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: shahadarsh/conf-details-svc:2.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080 
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: CONFERENCE_NAME
          value: "green"
