apiVersion: v1 
kind: Pod 
metadata:
  name: conference-details-service
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: server
    image: conference-details-service:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 8080 
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
