apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
spec:
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
spec:
  type: LoadBalancer
  selector:
    app: docker-registry
  ports:
  - name: http
    port: 80
    targetPort: 80
  

