apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: conference-website
spec:
  template:
    metadata:
      labels:
        app: conference-website
    spec:
      containers:
        - name: server
          image: us.gcr.io/adarsh-shah-playground/conference-website:latest
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: CONFERENCE_DETAILS_SERVICE_ADDR 
            value: "conference-details-service:9555"
          - name: SCHEDULE_SERVICE_ADDR
            value: "schedule-service:3550"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: conference-website
spec:
  type: ClusterIP
  selector:
    app: conference-website
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conference-website-external
spec:
  type: LoadBalancer
  selector:
    app: conference-website
  ports:
  - name: http
    port: 80
    targetPort: 8080
