apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: conference-details-service
spec:
  template:
    metadata:
      labels:
        app: conference-details-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: us.gcr.io/adarsh-shah-playground/conference-details-service:latest
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: conference-details-service
spec:
  type: ClusterIP
  selector:
    app: conference-details-service
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
