apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: schedule-service
spec:
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: us.gcr.io/adarsh-shah-playground/schedule-service:latest
        ports:
        - containerPort: 8080 
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service 
spec:
  type: ClusterIP
  selector:
    app: schedule-service 
  ports:
  - name: http
    port: 80
    targetPort: 8080
