apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-service
spec:
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: product-catalog-service
        ports:
        - containerPort: 3550
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
